server:
    port: 8082

management:
    endpoints:
        web:
            exposure:
                include: info
    endpoint:
        info:
            enabled: true
spring:
    application:
        name: user-service

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka

secret:
    message: "{cipher}5bf7292fd2a07b1fcd735cdbc981c21025efe1fd4344f62d604f70870f2866bd"
